name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: podman build -t katc -t katc-${{ github.run_id }} .
      - run: podman image save katc --output katc-${{ github.run_id }}.tar --format oci-archive
      - uses: actions/upload-artifact@v4
        with:
          path: katc-${{ github.run_id }}.tar
