name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: podman build -t katc .
      - run: podman image save katc --output katc.tar --format oci-archive
      - uses: actions/upload-artifact@v4
        with:
          name: katc-${{ github.run_id }}
          path: katc.tar
